[nfs]
172.31.43.60 ansible_ssh_user=ec2-user

[webservers]
172.31.32.47 ansible_ssh_user=ec2-user
172.31.46.214 ansible_ssh_user=ec2-user

[db]
172.31.42.192 ansible_ssh_user=ubuntu 

[lb]
172.31.36.7 ansible_ssh_user=ec2-user