- name: import common file
  import_playbook: ../static-assignments/common.yml

- name: import env-vars file
  import_playbook: ../dynamic-assignment/env-vars.yml

- name: import database file
  import_playbook: ../static-assignments/db.yml

- name: import webservers
  import_playbook: ../static-assignments/uat-webservers.yml

- name: Loadbalancers assignment
  hosts: lb
  import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required
